In [1]:
#importing the Libraies
import numpy as np
import matplotlib.pyplot as plt
import pandas as pd

In [2]:
dataset=pd.read_csv("CKD.csv")

In [3]:
dataset

,age,bp,sg,al,su,rbc,pc,pcc,ba,bgr,...,pcv,wc,rc,htn,dm,cad,appet,pe,ane,classification
0,2.000000,76.459948,c,3.0,0.0,normal,abnormal,notpresent,notpresent,148.112676,...,38.868902,8408.191126,4.705597,no,no,no,yes,yes,no,yes
1,3.000000,76.459948,c,2.0,0.0,normal,normal,notpresent,notpresent,148.112676,...,34.000000,12300.000000,4.705597,no,no,no,yes,poor,no,yes
2,4.000000,76.459948,a,1.0,0.0,normal,normal,notpresent,notpresent,99.000000,...,34.000000,8408.191126,4.705597,no,no,no,yes,poor,no,yes
3,5.000000,76.459948,d,1.0,0.0,normal,normal,notpresent,notpresent,148.112676,...,38.868902,8408.191126,4.705597,no,no,no,yes,poor,yes,yes
4,5.000000,50.000000,c,0.0,0.0,normal,normal,notpresent,notpresent,148.112676,...,36.000000,12400.000000,4.705597,no,no,no,yes,poor,no,yes
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
394,51.492308,70.000000,a,0.0,0.0,normal,normal,notpresent,notpresent,219.000000,...,37.000000,9800.000000,4.400000,no,no,no,yes,poor,no,yes
395,51.492308,70.000000,c,0.0,2.0,normal,normal,notpresent,notpresent,220.000000,...,27.000000,8408.191126,4.705597,yes,yes,no,yes,poor,yes,yes
396,51.492308,70.000000,c,3.0,0.0,normal,normal,notpresent,notpresent,110.000000,...,26.000000,9200.000000,3.400000,yes,yes,no,poor,poor,no,yes
397,51.492308,90.000000,a,0.0,0.0,normal,normal,notpresent,notpresent,207.000000,...,38.868902,8408.191126,4.705597,yes,yes,no,yes,poor,yes,yes
398,51.492308,80.000000,a,0.0,0.0,normal,normal,notpresent,notpresent,100.000000,...,53.000000,8500.000000,4.900000,no,no,no,yes,poor,no,no

In [4]:
dataset=pd.get_dummies(dataset,drop_first=True)

In [5]:
dataset

,age,bp,al,su,bgr,bu,sc,sod,pot,hrmo,...,pc_normal,pcc_present,ba_present,htn_yes,dm_yes,cad_yes,appet_yes,pe_yes,ane_yes,classification_yes
0,2.000000,76.459948,3.0,0.0,148.112676,57.482105,3.077356,137.528754,4.627244,12.518156,...,False,False,False,False,False,False,True,True,False,True
1,3.000000,76.459948,2.0,0.0,148.112676,22.000000,0.700000,137.528754,4.627244,10.700000,...,True,False,False,False,False,False,True,False,False,True
2,4.000000,76.459948,1.0,0.0,99.000000,23.000000,0.600000,138.000000,4.400000,12.000000,...,True,False,False,False,False,False,True,False,False,True
3,5.000000,76.459948,1.0,0.0,148.112676,16.000000,0.700000,138.000000,3.200000,8.100000,...,True,False,False,False,False,False,True,False,True,True
4,5.000000,50.000000,0.0,0.0,148.112676,25.000000,0.600000,137.528754,4.627244,11.800000,...,True,False,False,False,False,False,True,False,False,True
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
394,51.492308,70.000000,0.0,0.0,219.000000,36.000000,1.300000,139.000000,3.700000,12.500000,...,True,False,False,False,False,False,True,False,False,True
395,51.492308,70.000000,0.0,2.0,220.000000,68.000000,2.800000,137.528754,4.627244,8.700000,...,True,False,False,True,True,False,True,False,True,True
396,51.492308,70.000000,3.0,0.0,110.000000,115.000000,6.000000,134.000000,2.700000,9.100000,...,True,False,False,True,True,False,False,False,False,True
397,51.492308,90.000000,0.0,0.0,207.000000,80.000000,6.800000,142.000000,5.500000,8.500000,...,True,False,False,True,True,False,True,False,True,True
398,51.492308,80.000000,0.0,0.0,100.000000,49.000000,1.000000,140.000000,5.000000,16.300000,...,True,False,False,False,False,False,True,False,False,False

In [6]:
dataset["classification_yes"].value_counts()

classification_yes
True     249
False    150
Name: count, dtype: int64

In [7]:
indep=dataset[["age","bp","al","su","bgr","bu","sc","sod","pot","hrmo"]]
dep=dataset["classification_yes"]

In [8]:
indep.shape

(399, 10)

In [9]:
dep

0       True
1       True
2       True
3       True
4       True
       ...
394     True
395     True
396     True
397     True
398    False
Name: classification_yes, Length: 399, dtype: bool

In [10]:
#split into training set and test
from sklearn.model_selection import train_test_split
X_train, X_test, y_train, y_test = train_test_split(indep, dep, test_size = 1/3, random_state = 0)

In [11]:
from sklearn.preprocessing import StandardScaler
sc = StandardScaler()
X_train_= sc.fit_transform(X_train)
X_test_= sc.transform(X_test)

In [12]:
from sklearn.svm import SVC
from sklearn.model_selection import GridSearchCV

param_grid = {'kernel':['linear','rbf','poly','sigmoid'], 
              'gamma':['auto','scale'],
              'C':[10,100,1000,2000,3000]}  
grid = GridSearchCV(SVC(), param_grid, refit = True, verbose = 3,n_jobs=-1,scoring='f1_weighted') 
   
# fitting the model for grid search 
grid.fit(X_train, y_train) 
re=grid.cv_results_
#print(re)
grid_predictions = grid.predict(X_test) 
   

from sklearn.metrics import confusion_matrix
cm = confusion_matrix(y_test, grid_predictions)



# print classification report 
from sklearn.metrics import classification_report
clf_report = classification_report(y_test, grid_predictions)
print(clf_report)

Fitting 5 folds for each of 40 candidates, totalling 200 fits
              precision    recall  f1-score   support

       False       0.94      0.98      0.96        51
        True       0.99      0.96      0.98        82

    accuracy                           0.97       133
   macro avg       0.97      0.97      0.97       133
weighted avg       0.97      0.97      0.97       133

In [ ]:
print(cm)

In [13]:
from sklearn.metrics import roc_auc_score

roc_auc_score(y_test,grid.predict_proba(X_test)[:,1])

AttributeError: This 'GridSearchCV' has no attribute 'predict_proba'

[CV 3/5] END ...C=10, gamma=auto, kernel=linear;, score=0.963 total time=   0.1s
[CV 2/5] END .....C=10, gamma=scale, kernel=rbf;, score=0.851 total time=   0.0s
[CV 3/5] END .....C=10, gamma=scale, kernel=rbf;, score=0.870 total time=   0.0s
[CV 5/5] END .....C=10, gamma=scale, kernel=rbf;, score=0.907 total time=   0.0s
[CV 4/5] END .C=10, gamma=scale, kernel=sigmoid;, score=0.434 total time=   0.0s
[CV 5/5] END .C=10, gamma=scale, kernel=sigmoid;, score=0.255 total time=   0.0s
[CV 5/5] END ..C=100, gamma=auto, kernel=linear;, score=0.962 total time=   1.0s
[CV 5/5] END .C=2000, gamma=auto, kernel=linear;, score=0.981 total time=   2.2s
[CV 1/5] END ....C=2000, gamma=auto, kernel=rbf;, score=0.527 total time=   0.0s
[CV 2/5] END ....C=2000, gamma=auto, kernel=rbf;, score=0.501 total time=   0.0s
[CV 3/5] END ....C=2000, gamma=auto, kernel=rbf;, score=0.519 total time=   0.0s
[CV 2/5] END C=3000, gamma=scale, kernel=linear;, score=0.962 total time=   0.6s
[CV 1/5] END ...C=3000, gamma=scale, kernel=rbf;, score=0.945 total time=   0.0s
[CV 2/5] END ...C=3000, gamma=scale, kernel=rbf;, score=0.924 total time=   0.0s
[CV 3/5] END ...C=3000, gamma=scale, kernel=rbf;, score=0.944 total time=   0.0s
[CV 4/5] END ...C=3000, gamma=scale, kernel=rbf;, score=0.962 total time=   0.0s
[CV 1/5] END ..C=3000, gamma=scale, kernel=poly;, score=0.927 total time=   0.0s
[CV 3/5] END ..C=3000, gamma=scale, kernel=poly;, score=0.944 total time=   0.0s
[CV 5/5] END ..C=3000, gamma=scale, kernel=poly;, score=0.981 total time=   0.0s
[CV 2/5] END C=3000, gamma=scale, kernel=sigmoid;, score=0.365 total time=   0.0s
[CV 4/5] END C=3000, gamma=scale, kernel=sigmoid;, score=0.408 total time=   0.0s
[CV 3/5] END ......C=10, gamma=auto, kernel=rbf;, score=0.519 total time=   0.0s
[CV 2/5] END .....C=10, gamma=auto, kernel=poly;, score=0.924 total time=   0.0s
[CV 4/5] END .....C=10, gamma=auto, kernel=poly;, score=0.962 total time=   0.0s
[CV 2/5] END ..C=10, gamma=auto, kernel=sigmoid;, score=0.501 total time=   0.0s
[CV 5/5] END ..C=10, gamma=scale, kernel=linear;, score=0.962 total time=   0.1s
[CV 1/5] END .....C=100, gamma=auto, kernel=rbf;, score=0.527 total time=   0.0s
[CV 2/5] END .....C=100, gamma=auto, kernel=rbf;, score=0.501 total time=   0.0s
[CV 3/5] END .....C=100, gamma=auto, kernel=rbf;, score=0.519 total time=   0.0s
[CV 4/5] END .....C=100, gamma=auto, kernel=rbf;, score=0.478 total time=   0.0s
[CV 1/5] END ....C=100, gamma=auto, kernel=poly;, score=0.854 total time=   0.0s
[CV 4/5] END ....C=100, gamma=auto, kernel=poly;, score=0.962 total time=   0.0s
[CV 2/5] END .C=100, gamma=auto, kernel=sigmoid;, score=0.501 total time=   0.0s
[CV 3/5] END .C=100, gamma=auto, kernel=sigmoid;, score=0.478 total time=   0.0s
[CV 1/5] END .C=100, gamma=scale, kernel=linear;, score=1.000 total time=   3.5s
[CV 2/5] END .C=100, gamma=scale, kernel=linear;, score=0.943 total time=   0.4s
[CV 5/5] END ...C=3000, gamma=scale, kernel=rbf;, score=0.981 total time=   0.0s
[CV 2/5] END ..C=3000, gamma=scale, kernel=poly;, score=0.924 total time=   0.0s
[CV 4/5] END ..C=3000, gamma=scale, kernel=poly;, score=0.962 total time=   0.0s
[CV 1/5] END C=3000, gamma=scale, kernel=sigmoid;, score=0.385 total time=   0.0s
[CV 3/5] END C=3000, gamma=scale, kernel=sigmoid;, score=0.351 total time=   0.0s
[CV 5/5] END C=3000, gamma=scale, kernel=sigmoid;, score=0.275 total time=   0.0s
[CV 5/5] END ...C=10, gamma=auto, kernel=linear;, score=0.962 total time=   0.1s
[CV 1/5] END ..C=10, gamma=scale, kernel=linear;, score=0.982 total time=   0.1s
[CV 1/5] END .C=100, gamma=auto, kernel=sigmoid;, score=0.487 total time=   0.0s
[CV 4/5] END .C=100, gamma=auto, kernel=sigmoid;, score=0.478 total time=   0.0s
[CV 5/5] END .C=100, gamma=scale, kernel=linear;, score=0.962 total time=   1.0s
[CV 1/5] END ....C=100, gamma=scale, kernel=rbf;, score=0.945 total time=   0.0s
[CV 4/5] END ....C=2000, gamma=auto, kernel=rbf;, score=0.478 total time=   0.0s
[CV 5/5] END ....C=2000, gamma=auto, kernel=rbf;, score=0.478 total time=   0.0s
[CV 1/5] END ...C=2000, gamma=auto, kernel=poly;, score=0.854 total time=   0.0s
[CV 2/5] END ...C=2000, gamma=auto, kernel=poly;, score=0.924 total time=   0.0s
[CV 3/5] END ...C=2000, gamma=auto, kernel=poly;, score=0.907 total time=   0.0s
[CV 4/5] END ...C=2000, gamma=auto, kernel=poly;, score=0.962 total time=   0.0s
[CV 5/5] END ...C=2000, gamma=auto, kernel=poly;, score=0.942 total time=   0.0s
[CV 1/5] END C=2000, gamma=auto, kernel=sigmoid;, score=0.487 total time=   0.0s
[CV 5/5] END C=2000, gamma=scale, kernel=linear;, score=0.981 total time=   2.3s
[CV 1/5] END ...C=2000, gamma=scale, kernel=rbf;, score=0.963 total time=   0.0s
[CV 2/5] END ...C=2000, gamma=scale, kernel=rbf;, score=0.924 total time=   0.0s
[CV 3/5] END ...C=2000, gamma=scale, kernel=rbf;, score=0.944 total time=   0.0s
[CV 5/5] END C=3000, gamma=scale, kernel=linear;, score=0.981 total time=   0.7s
[CV 1/5] END ......C=10, gamma=auto, kernel=rbf;, score=0.527 total time=   0.0s
[CV 3/5] END ..C=10, gamma=auto, kernel=sigmoid;, score=0.478 total time=   0.0s
[CV 2/5] END ..C=10, gamma=scale, kernel=linear;, score=0.943 total time=   0.1s
[CV 5/5] END ....C=100, gamma=auto, kernel=poly;, score=0.942 total time=   0.0s
[CV 2/5] END ....C=100, gamma=scale, kernel=rbf;, score=0.924 total time=   0.0s
[CV 3/5] END ....C=100, gamma=scale, kernel=rbf;, score=0.944 total time=   0.0s
[CV 1/5] END ...C=100, gamma=scale, kernel=poly;, score=1.000 total time=   0.0s
[CV 2/5] END ...C=100, gamma=scale, kernel=poly;, score=0.924 total time=   0.0s
[CV 3/5] END ...C=100, gamma=scale, kernel=poly;, score=0.963 total time=   0.0s
[CV 4/5] END ...C=100, gamma=scale, kernel=poly;, score=0.962 total time=   0.0s
[CV 2/5] END C=100, gamma=scale, kernel=sigmoid;, score=0.365 total time=   0.0s
[CV 3/5] END C=100, gamma=scale, kernel=sigmoid;, score=0.351 total time=   0.0s
[CV 1/5] END .C=1000, gamma=auto, kernel=linear;, score=1.000 total time=   2.4s
[CV 2/5] END .C=1000, gamma=auto, kernel=linear;, score=0.943 total time=   0.9s
[CV 4/5] END C=3000, gamma=scale, kernel=linear;, score=0.943 total time=   1.1s
[CV 1/5] END ...C=10, gamma=auto, kernel=linear;, score=0.982 total time=   0.1s
[CV 4/5] END .....C=10, gamma=scale, kernel=rbf;, score=0.833 total time=   0.0s
[CV 2/5] END ....C=10, gamma=scale, kernel=poly;, score=0.887 total time=   0.0s
[CV 5/5] END ....C=10, gamma=scale, kernel=poly;, score=0.907 total time=   0.0s
[CV 4/5] END ..C=100, gamma=auto, kernel=linear;, score=0.943 total time=   0.5s
[CV 2/5] END C=1000, gamma=auto, kernel=sigmoid;, score=0.501 total time=   0.0s
[CV 3/5] END C=1000, gamma=auto, kernel=sigmoid;, score=0.478 total time=   0.0s
[CV 1/5] END C=1000, gamma=scale, kernel=linear;, score=1.000 total time=   2.3s
[CV 2/5] END C=1000, gamma=scale, kernel=linear;, score=0.943 total time=   1.0s
[CV 3/5] END C=1000, gamma=scale, kernel=linear;, score=0.944 total time=   0.4s
[CV 4/5] END C=1000, gamma=scale, kernel=linear;, score=0.925 total time=   0.5s
[CV 4/5] END ......C=10, gamma=auto, kernel=rbf;, score=0.478 total time=   0.0s
[CV 5/5] END .....C=10, gamma=auto, kernel=poly;, score=0.942 total time=   0.0s
[CV 5/5] END ..C=10, gamma=auto, kernel=sigmoid;, score=0.478 total time=   0.0s
[CV 1/5] END .....C=10, gamma=scale, kernel=rbf;, score=0.909 total time=   0.0s
[CV 1/5] END ....C=10, gamma=scale, kernel=poly;, score=0.891 total time=   0.0s
[CV 4/5] END ....C=10, gamma=scale, kernel=poly;, score=0.814 total time=   0.0s
[CV 2/5] END .C=10, gamma=scale, kernel=sigmoid;, score=0.381 total time=   0.0s
[CV 1/5] END ..C=100, gamma=auto, kernel=linear;, score=1.000 total time=   3.4s
[CV 3/5] END C=3000, gamma=scale, kernel=linear;, score=0.944 total time=   1.6s
[CV 2/5] END ...C=10, gamma=auto, kernel=linear;, score=0.943 total time=   0.1s
[CV 5/5] END .....C=100, gamma=auto, kernel=rbf;, score=0.478 total time=   0.0s
[CV 2/5] END ....C=100, gamma=auto, kernel=poly;, score=0.924 total time=   0.0s
[CV 3/5] END ....C=100, gamma=auto, kernel=poly;, score=0.907 total time=   0.0s
[CV 3/5] END .C=100, gamma=scale, kernel=linear;, score=0.944 total time=   0.1s
[CV 4/5] END .C=100, gamma=scale, kernel=linear;, score=0.943 total time=   0.6s
[CV 4/5] END ...C=1000, gamma=scale, kernel=rbf;, score=0.942 total time=   0.0s
[CV 5/5] END ...C=1000, gamma=scale, kernel=rbf;, score=0.981 total time=   0.0s
[CV 1/5] END ..C=1000, gamma=scale, kernel=poly;, score=0.982 total time=   0.0s
[CV 2/5] END ..C=1000, gamma=scale, kernel=poly;, score=0.943 total time=   0.0s
[CV 3/5] END ..C=1000, gamma=scale, kernel=poly;, score=0.963 total time=   0.0s
[CV 4/5] END ..C=1000, gamma=scale, kernel=poly;, score=0.962 total time=   0.0s
[CV 5/5] END ..C=1000, gamma=scale, kernel=poly;, score=0.981 total time=   0.0s
[CV 1/5] END C=1000, gamma=scale, kernel=sigmoid;, score=0.385 total time=   0.0s
[CV 2/5] END C=1000, gamma=scale, kernel=sigmoid;, score=0.365 total time=   0.0s
[CV 3/5] END C=1000, gamma=scale, kernel=sigmoid;, score=0.351 total time=   0.0s
[CV 4/5] END C=1000, gamma=scale, kernel=sigmoid;, score=0.408 total time=   0.0s
[CV 5/5] END C=1000, gamma=scale, kernel=sigmoid;, score=0.275 total time=   0.0s
[CV 1/5] END .C=2000, gamma=auto, kernel=linear;, score=1.000 total time=   4.6s
[CV 2/5] END .C=2000, gamma=auto, kernel=linear;, score=0.962 total time=   0.8s
[CV 3/5] END .C=2000, gamma=auto, kernel=linear;, score=0.944 total time=   1.3s
[CV 4/5] END .C=2000, gamma=auto, kernel=linear;, score=0.925 total time=   0.8s
[CV 4/5] END ...C=10, gamma=auto, kernel=linear;, score=0.943 total time=   0.1s
[CV 3/5] END ....C=10, gamma=scale, kernel=poly;, score=0.889 total time=   0.0s
[CV 1/5] END .C=10, gamma=scale, kernel=sigmoid;, score=0.370 total time=   0.0s
[CV 3/5] END .C=10, gamma=scale, kernel=sigmoid;, score=0.396 total time=   0.0s
[CV 3/5] END ..C=100, gamma=auto, kernel=linear;, score=0.944 total time=   0.1s
[CV 4/5] END C=100, gamma=scale, kernel=sigmoid;, score=0.421 total time=   0.0s
[CV 5/5] END C=100, gamma=scale, kernel=sigmoid;, score=0.275 total time=   0.0s
[CV 3/5] END .C=1000, gamma=auto, kernel=linear;, score=0.944 total time=   0.5s
[CV 4/5] END .C=1000, gamma=auto, kernel=linear;, score=0.925 total time=   0.6s
[CV 2/5] END C=2000, gamma=auto, kernel=sigmoid;, score=0.501 total time=   0.0s
[CV 3/5] END C=2000, gamma=auto, kernel=sigmoid;, score=0.478 total time=   0.0s
[CV 4/5] END C=2000, gamma=auto, kernel=sigmoid;, score=0.478 total time=   0.0s
[CV 5/5] END C=2000, gamma=auto, kernel=sigmoid;, score=0.478 total time=   0.0s
[CV 1/5] END C=2000, gamma=scale, kernel=linear;, score=1.000 total time=   4.7s
[CV 2/5] END C=2000, gamma=scale, kernel=linear;, score=0.962 total time=   0.9s
[CV 3/5] END C=2000, gamma=scale, kernel=linear;, score=0.944 total time=   1.3s
[CV 4/5] END C=2000, gamma=scale, kernel=linear;, score=0.925 total time=   0.8s
[CV 2/5] END ......C=10, gamma=auto, kernel=rbf;, score=0.501 total time=   0.0s
[CV 1/5] END .....C=10, gamma=auto, kernel=poly;, score=0.854 total time=   0.0s
[CV 3/5] END .....C=10, gamma=auto, kernel=poly;, score=0.907 total time=   0.0s
[CV 1/5] END ..C=10, gamma=auto, kernel=sigmoid;, score=0.487 total time=   0.0s
[CV 3/5] END ..C=10, gamma=scale, kernel=linear;, score=0.963 total time=   0.1s
[CV 2/5] END ..C=100, gamma=auto, kernel=linear;, score=0.943 total time=   0.4s
[CV 2/5] END ....C=1000, gamma=auto, kernel=rbf;, score=0.501 total time=   0.0s
[CV 3/5] END ....C=1000, gamma=auto, kernel=rbf;, score=0.519 total time=   0.0s
[CV 4/5] END ....C=1000, gamma=auto, kernel=rbf;, score=0.478 total time=   0.0s
[CV 5/5] END ....C=1000, gamma=auto, kernel=rbf;, score=0.478 total time=   0.0s
[CV 1/5] END ...C=1000, gamma=auto, kernel=poly;, score=0.854 total time=   0.0s
[CV 2/5] END ...C=1000, gamma=auto, kernel=poly;, score=0.924 total time=   0.0s
[CV 3/5] END ...C=1000, gamma=auto, kernel=poly;, score=0.907 total time=   0.0s
[CV 4/5] END ...C=1000, gamma=auto, kernel=poly;, score=0.962 total time=   0.0s
[CV 5/5] END ...C=1000, gamma=auto, kernel=poly;, score=0.942 total time=   0.0s
[CV 1/5] END C=1000, gamma=auto, kernel=sigmoid;, score=0.487 total time=   0.0s
[CV 4/5] END C=1000, gamma=auto, kernel=sigmoid;, score=0.478 total time=   0.0s
[CV 5/5] END C=1000, gamma=auto, kernel=sigmoid;, score=0.478 total time=   0.0s
[CV 5/5] END C=1000, gamma=scale, kernel=linear;, score=0.981 total time=   1.8s
[CV 1/5] END ...C=1000, gamma=scale, kernel=rbf;, score=0.982 total time=   0.0s
[CV 2/5] END ...C=1000, gamma=scale, kernel=rbf;, score=0.924 total time=   0.0s
[CV 3/5] END ...C=1000, gamma=scale, kernel=rbf;, score=0.963 total time=   0.0s
[CV 5/5] END .C=3000, gamma=auto, kernel=linear;, score=0.981 total time=   0.8s
[CV 1/5] END ....C=3000, gamma=auto, kernel=rbf;, score=0.527 total time=   0.0s
[CV 2/5] END ....C=3000, gamma=auto, kernel=rbf;, score=0.501 total time=   0.0s
[CV 3/5] END ....C=3000, gamma=auto, kernel=rbf;, score=0.519 total time=   0.0s
[CV 4/5] END ....C=3000, gamma=auto, kernel=rbf;, score=0.478 total time=   0.0s
[CV 5/5] END ....C=3000, gamma=auto, kernel=rbf;, score=0.478 total time=   0.0s
[CV 1/5] END ...C=3000, gamma=auto, kernel=poly;, score=0.854 total time=   0.0s
[CV 2/5] END ...C=3000, gamma=auto, kernel=poly;, score=0.924 total time=   0.0s
[CV 3/5] END ...C=3000, gamma=auto, kernel=poly;, score=0.907 total time=   0.0s
[CV 4/5] END ...C=3000, gamma=auto, kernel=poly;, score=0.962 total time=   0.0s
[CV 5/5] END ...C=3000, gamma=auto, kernel=poly;, score=0.942 total time=   0.0s
[CV 1/5] END C=3000, gamma=auto, kernel=sigmoid;, score=0.487 total time=   0.0s
[CV 2/5] END C=3000, gamma=auto, kernel=sigmoid;, score=0.501 total time=   0.0s
[CV 3/5] END C=3000, gamma=auto, kernel=sigmoid;, score=0.478 total time=   0.0s
[CV 4/5] END C=3000, gamma=auto, kernel=sigmoid;, score=0.478 total time=   0.0s
[CV 5/5] END C=3000, gamma=auto, kernel=sigmoid;, score=0.478 total time=   0.0s
[CV 1/5] END C=3000, gamma=scale, kernel=linear;, score=1.000 total time=  10.0s
[CV 5/5] END ......C=10, gamma=auto, kernel=rbf;, score=0.478 total time=   0.0s
[CV 4/5] END ..C=10, gamma=auto, kernel=sigmoid;, score=0.478 total time=   0.0s
[CV 4/5] END ..C=10, gamma=scale, kernel=linear;, score=0.943 total time=   0.1s
[CV 5/5] END .C=100, gamma=auto, kernel=sigmoid;, score=0.478 total time=   0.0s
[CV 4/5] END ....C=100, gamma=scale, kernel=rbf;, score=0.962 total time=   0.0s
[CV 5/5] END ....C=100, gamma=scale, kernel=rbf;, score=0.962 total time=   0.0s
[CV 5/5] END ...C=100, gamma=scale, kernel=poly;, score=0.962 total time=   0.0s
[CV 1/5] END C=100, gamma=scale, kernel=sigmoid;, score=0.385 total time=   0.0s
[CV 5/5] END .C=1000, gamma=auto, kernel=linear;, score=0.981 total time=   1.8s
[CV 1/5] END ....C=1000, gamma=auto, kernel=rbf;, score=0.527 total time=   0.0s
[CV 4/5] END ...C=2000, gamma=scale, kernel=rbf;, score=0.962 total time=   0.0s
[CV 5/5] END ...C=2000, gamma=scale, kernel=rbf;, score=0.981 total time=   0.0s
[CV 1/5] END ..C=2000, gamma=scale, kernel=poly;, score=0.982 total time=   0.0s
[CV 2/5] END ..C=2000, gamma=scale, kernel=poly;, score=0.924 total time=   0.0s
[CV 3/5] END ..C=2000, gamma=scale, kernel=poly;, score=0.963 total time=   0.0s
[CV 4/5] END ..C=2000, gamma=scale, kernel=poly;, score=0.962 total time=   0.0s
[CV 5/5] END ..C=2000, gamma=scale, kernel=poly;, score=0.981 total time=   0.0s
[CV 1/5] END C=2000, gamma=scale, kernel=sigmoid;, score=0.385 total time=   0.0s
[CV 2/5] END C=2000, gamma=scale, kernel=sigmoid;, score=0.365 total time=   0.0s
[CV 3/5] END C=2000, gamma=scale, kernel=sigmoid;, score=0.351 total time=   0.0s
[CV 4/5] END C=2000, gamma=scale, kernel=sigmoid;, score=0.408 total time=   0.0s
[CV 5/5] END C=2000, gamma=scale, kernel=sigmoid;, score=0.275 total time=   0.0s
[CV 1/5] END .C=3000, gamma=auto, kernel=linear;, score=1.000 total time=  10.3s
[CV 2/5] END .C=3000, gamma=auto, kernel=linear;, score=0.962 total time=   0.4s
[CV 3/5] END .C=3000, gamma=auto, kernel=linear;, score=0.944 total time=   1.3s
[CV 4/5] END .C=3000, gamma=auto, kernel=linear;, score=0.943 total time=   0.9s